spring.application.name=ai-review

review.python-ai-url=http://python-ai:8000
review.github-token=${GITHUB_TOKEN}
review.webhook-secret=${WEBHOOK_SECRET}
review.max-retry=3

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

review.reviewed-commit-ttl=86400