spring.application.name=ai-review

review.api-key=${GEMINI_API_KEY}
review.github-token=${GITHUB_TOKEN}
review.webhook-secret=${WEBHOOK_SECRET}
review.ai-model=gemini-2.5-flash
review.max-retry=3

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

review.reviewed-commit-ttl=86400